print("---------------------")
print("Tugas 1 SISOP Kelas-A")
print("---------------------")
print("Nama: Valentino Belardo")
print("NPM: 21083010109")
print("--------------------")
print("notes:")
print("-------------------")
print("Halo dunia!")
print("Ini adalah skrip Bash pertamaku di Linux")
